# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: #welcome
    weight: 10
  - name: News
    url: post
    weight: 20
  - name: People
    identifier: people
    weight: 30
  - name: Projects
    identifier: projects
    url: project
    weight: 40
  - name: AI in Education
    parent: projects
    url: project/ai-education/
    weight: 10
  - name: Trustworthy AI
    parent: projects
    url: project/opacity-ml/
    weight: 20
  - name: Value Alignment
    parent: projects
    url: project/human-control-ai/
    weight: 30
  - name: Members
    parent: people
    url: people/
    weight: 10
  - name: Visiting
    parent: people
    url: visiting/
    weight: 20
  - name: Activities
    identifier: activities
    weight: 50
  - name: Workshops
    parent: activities
    url: event/
    weight: 10
  - name: Reading Groups
    parent: activities
    url: activities/reading-groups/
    weight: 20
  - name: Publications
    url: publication
    weight: 60
  #- name: Contact
   # url: contact
    #weight: 70
