# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: #welcome
    weight: 10
  - name: News
    url: post
    weight: 20
  - name: People
    url: people
    weight: 30
  - name: Project
    url: project
    identifier: projects
    weight: 40
#  - name: AI, animals, and other non-human intelligences
#    parent: cluster
#    url: cluster/animals
 #   weight: 10
  - name: Value Alignment
    parent: projects
    url: project/value-alignment
    weight: 20
  - name: AI in Education
    parent: projects
    url: project/ai-education
    weight: 30
  - name: Events
    url: event
    weight: 50
  - name: Publications
    url: publication
    weight: 60
  #- name: Contact
   # url: contact
    #weight: 70

#  - name: People
#    identifier: people
#    weight: 30
#  - name: Members
#    parent: people
#    url: people/
#    weight: 10
#  - name: Visiting
#    parent: people
#    url: visiting/
#    weight: 20
